/* eslint-disable react/no-unescaped-entities */

import BitnormPaper from '../BitnormPaper';
import Wrapper from '../Wrapper';

export default function Cookie() {
    return (
        <Wrapper>
            <BitnormPaper title="BitNorm Cookie Policy">
                <>
                    <p>
                        <strong>
                            [First build up: Wednesday, 15 July 2020]
                        </strong>
                    </p>
                    <p>
                        <strong>What Are Cookies?</strong>
                    </p>
                    <p>
                        Cookies are files with small amount of data, which may
                        include an anonymous unique identifier. Cookies are sent
                        to your browser from the Technology Platform and stored
                        on your computer's hard drive.
                    </p>
                    <p>
                        Cookies enable the Technology Platform to remember your
                        actions and preferences (such as login, language, font
                        size and other display preferences) over a period of
                        time, so you don’t have to keep re-entering them
                        whenever you come back to the Technology Platform or
                        browse from one page to another.
                    </p>
                    <p>
                        <strong>How Do We Use Cookies?</strong>
                    </p>
                    <p>
                        This Technology Platform uses Google Analytics, a web
                        analytics service provided by Google, Inc. (“Google”).
                        Google Analytics uses “cookies”, which are text files
                        placed on your computer, to help the Technology Platform
                        analyze how users use the site. The information
                        generated by the cookie about your use of different
                        sites (including your IP address) will be transmitted to
                        and stored by Google on servers in the United States.
                        Google will use this information for the purpose of
                        evaluating your use of sites, compiling reports on sites
                        activity for sites operators and providing other
                        services relating to sites activity and internet usage.
                        Google may also transfer this information to third
                        parties where required to do so by law, or where such
                        third parties process the information on Google's
                        behalf. Google will not associate your IP address with
                        any other data held by Google. You may refuse the use of
                        cookies by selecting the appropriate settings on your
                        browser, however, please note that if you do this you
                        may not be able to use the full functionality of the
                        Technology Platform. By using the Technology Platform,
                        you consent to the processing of data about you by
                        Google in the manner and for the purposes set out above.
                    </p>
                    <p>
                        <strong>How to Control Cookies?</strong>
                    </p>
                    <p>
                        You can control and/or delete cookies if you wish. You
                        can delete all cookies that are already on your computer
                        and you can set most browsers to prevent them from being
                        stored therein. If you do this, however, you may have to
                        manually adjust some preferences every time you visit
                        the Technology Platform and some services and
                        functionalities may not work.
                    </p>
                </>
            </BitnormPaper>
        </Wrapper>
    );
}
